spring:
  datasource:
  #此处版本问题添加了cj
    driver-class-name: com.mysql.cj.jdbc.Driver
  #连接的数据库类型，本机端口号，库，编码方式
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password

 #此处jpa下的show使得sql语句被显示，format则时期变得整齐易读
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  #服务器端口号
server:
  port: 8181